sudo : required
services:
  - docker

before_install:
   - docker build -t satishbhonsle/docker-react -f Dockerfile.dev .

script:
   - docker run satishbhonsle/docker-react npm run test -- --coverage 